name: alaa
description: wtf
assets:
  object:
    - name: alaaobj
      prop: nooo
      vars:
        instance_var_struct:
          sprite_index: spr_ball
        event_scripts:
          create: alaa/create.vsl
          step: alaa/step.vsl
          draw: draw_self

  vsl: []
